### ISSUE TITLE
Step 6: appspec.yml not found.

### ISSUE THREAD

**Issue by robbylucia** [techpivot/aws-code-deploy#10]
**Full**
Step 6: Checking Application Source
✖ The specified source directory "/home/circleci/project" does not contain an "appspec.yml" in the application root.

I've been struggling to get this to work for a while. I wasn't able to get the example circle.yml file to work. Could a more complete example be provided? I may have broke something in the process, as I haven't gotten environment variables to be set without doing them manually through CircleCI's UI.

**Comment by virgofx** [comment]
Prior to bundling your application, it checks to make sure you have an `appspec.yml` which is required on the other side (the deployment side) It would fail otherwise. Do you have an `appspec.yml` in your project root? If not, you're missing a big piece of the AWS Code Deploy part --- which is really outside the scope of this project. This is more of a wrapper to help bundling things up quickly in CircleCI and pushing to code deploy which then does the next part of pushing to your servers.

**Comment by gregorskii** [comment]
Same as above, I had this error initially, but I cp-ed the appspec.yml from my project root into the dist folder it was zipping. Solved it.

**Comment by virgofx** [comment]
Thanks for feedback. Marking as closed.
